### PR TITLE
JOL24: Update manager role email

### PR DESCRIPTION
**Pull request by SalamanderHP**

### CODE REVIEW

**Comment by SalamanderHP** [comment]
Screenshot from 2022-02-13 02-01-41

**Comment by SalamanderHP** [comment]
Screenshot from 2022-02-13 02-15-57
Nếu account chưa signin vào hệ thống

**Comment by SalamanderHP** [comment]
@kkinggmann @sagara11 review t

**Comment by SalamanderHP** [comment]
@kkinggmann review t nhé

**Review by kkinggmann — APPROVED** [review]

**Pull request merged**
